mqtt:
  enabled: true
  host: 192.168.4.18
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 45

tls:
  enabled: true

auth:
  enabled: true
  cookie_secure: true
  session_length: 86400
  refresh_time: 43200
  hash_iterations: 600000

birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 15
  mode: objects
  inactivity_threshold: 30
  layout:
    scaling_factor: 2.0
    max_cameras: 1

go2rtc:
  streams:
    Doorbell:
      - ffmpeg:http://192.168.4.254/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_DOORBELL_USER}&password={FRIGATE_DOORBELL_PASS}#video=copy#audio=copy#audio=opus
      - rtsp://192.168.4.245/Preview_01_sub
      - ffmpeg:doorbell#audio=opus
    Doorbell_sub:
      - ffmpeg:http://192.168.4.254/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_DOORBELL_USER}&password={FRIGATE_DOORBELL_PASS}
    Front_Yard:
      - ffmpeg:http://192.168.4.113/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_FRONT_YARD_USER}&password={FRIGATE_FRONT_YARD_PASS}#video=copy#audio=copy#audio=opus
    Front_Yard_sub:
      - ffmpeg:http://192.168.4.113/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_FRONT_YARD_USER}&password={FRIGATE_FRONT_YARD_PASS}#video=copy
    Driveway_Cam:
      - ffmpeg:http://192.168.4.190/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_DRIVEWAY_USER}&password={FRIGATE_DRIVEWAY_PASS}#video=copy#audio=copy#audio=opus
    Driveway_Cam_sub:
      - ffmpeg:http://192.168.4.190/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_DRIVEWAY_USER}&password={FRIGATE_DRIVEWAY_PASS}#video=copy
    Backyard:
      - ffmpeg:http://192.168.4.112/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_BACKYARD_USER}&password={FRIGATE_BACKYARD_PASS}#video=copy#audio=copy#audio=opus
    Backyard_sub:
      - ffmpeg:http://192.168.4.112/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_BACKYARD_USER}&password={FRIGATE_BACKYARD_PASS}#video=copy
    Backyard_Cam_2:
      - ffmpeg:http://192.168.4.205/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_BACKYARD2_USER}&password={FRIGATE_BACKYARD2_PASS}#video=copy#audio=copy#audio=opus
    Backyard_Cam_2_sub:
      - ffmpeg:http://192.168.4.205/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_BACKYARD2_USER}&password={FRIGATE_BACKYARD2_PASS}#video=copy
    #Patio_Cam:
    #  - rtsp://root:[email protected]:8554/unicast
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"


cameras:
  Doorbell:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 35
      contour_area: 25
      improve_contrast: true
  Front_Yard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Yard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 35
      contour_area: 25
      improve_contrast: true
    zones:
      Front_Yard_Main:
        coordinates: 
          0,0.43,0.16,0.396,0.273,0.377,0.342,0.372,0.409,0.376,0.48,0.382,0.568,0.403,0.659,0.424,0.762,0.443,0.837,0.469,0.851,0.478,0.872,0.485,0.601,0.698,0.884,0.869,0.791,0.999,0,0.998
        loitering_time: 0
      Driveway_Main:
        coordinates: 0.363,0.368,0.686,0.332,0.928,0.407,0.925,0.506,0.694,0.431,0.486,0.383
        loitering_time: 0
      Walkway:
        coordinates: 0.868,0.492,0.604,0.697,0.999,0.924,0.999,0.401,0.889,0.396
        loitering_time: 0
      Melrose_Street:
        coordinates: 
          0,0.429,0.006,0.369,0.482,0.3,0.659,0.285,0.793,0.275,0.798,0.327,0.617,0.338,0.365,0.37,0.193,0.388
        loitering_time: 0
  Driveway_Cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_Cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_Cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.267,0.148,0.534,0.13,0.439,0.001,0.111,0,0.126,0.14
    zones:
      driveway_main_zone:
        coordinates: 
          0.009,0.26,0.231,0.185,0.947,0.468,0.999,0.541,0.999,0.996,0.363,0.996,0.003,0.35
        loitering_time: 0
    objects:
      filters:
        car:
          mask: 1,0.543,0.675,0.36,0.707,0.188,0.797,0.175,0.928,0.207,0.997,0.222
  Backyard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 50
      contour_area: 25
      improve_contrast: true
      mask:
        - 0.311,0.237,0.31,0.237,0.282,0.176,0.684,0.142,0.863,0.207
        - 0.532,0.245,0.545,0.399,0.787,0.402,0.786,0.228
    objects:
      filters:
        person:
          mask: 0.252,0.218,0.263,0.163,0.339,0.144,0.68,0.12,0.869,0.205,0.865,0.22,0.305,0.259
    zones:
      Back_door:
        coordinates: 0.022,0.256,0.108,0.226,0.155,0.513,0.083,0.544
        loitering_time: 0
      Back_patio:
        coordinates: 
          0.14,0.416,0.182,0.394,0.257,0.507,0.326,0.606,0.547,0.477,0.723,0.569,0.891,0.685,0.71,1,0.411,0.996,0.305,0.823,0.185,0.546
        loitering_time: 0
  Backyard_Cam_2:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard_Cam_2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Backyard_Cam_2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 50
      contour_area: 58
      improve_contrast: true
    zones:
      My_backyard_property:
        coordinates: 
          0.377,0.125,0.654,0.175,0.855,0.197,0.999,0.245,0.999,0.999,0.001,0.999,0.001,0.183
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - sports ball
#  Patio_Cam:
#    ffmpeg:
#      inputs:
#        - path: rtsp://root:[email protected]:8554/unicast
#          input_args: preset-rtsp-restream
#          roles:
#          - record
#          - detect
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 14
      mode: motion
objects:
  track:
    - person
    - car
    - bird
    - bicycle
    - cat
    - dog
    - sports ball
detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  width: 640
  height: 480
  fps: 4
review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - person
      - dog
      - cat
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30
  quality: 60
motion:
  enabled: true
  threshold: 30
  lightning_threshold: 0.8
  contour_area: 25
  improve_contrast: true
version: 0.14

camera_groups:
  Birdseye:
    order: 1
    icon: LuEye
    cameras:
      - birdseye
      - Backyard
      - Front_Yard
      - Driveway_Cam
      - Backyard_Cam_2
